language: objective-c
os: osx
xcode_project: BXUIKit.xcodeproj
before_install:
- gem install xcpretty
- brew install jq
install: sh download_bxswiftutils.sh
env:
  global:
    # GH_TOKEN
    - secure: cd5/746x8YL71FHEEqVZhj/jfj2fRms9/F5Lh7c/dbNAQ/RwHIHQL9nXELRgImQAzRS8Jvm1Om3tNl5iJ7/I71Ij/wLDp3ryQso/vQGd7c6sMODvVPYnXhXiQ7SVxxyYxpnp8v//87C6NEczmmCoY2iRSHDWBZI3romg/T5TYc9Y979JYy28YvoTUInaySTmOHikp7Sa8x17zdhgAFqiA4UO4qfR48DloJsc6qcvhXA8QEvW9exrvTkvGvpiFM1Ag7H/7+iXterY2NaFJlyyhqdU5yVothEmLXTjsauJycc3jiQuHff2dUTyaphaPCk4Ldg9bu2wd6q7f+t7JWWHRpf96wBvK3wWlhMRgtss3J32BqoUgPDzTa67eNc3XwkFeML6icqRPeypPaOO6+I8Qm4h/uexXXycuk2iv9DvH29S1JPtx4BHfITzkDjIb9u013Xl7LpBaO39R3CYUiJaMsYb3tDYqDgnyqJLPDHVMUB0TYBYTEEew6zTG1XRtyH29fZ+pEtWAqwR9vFhI11x3Y3dAuTA2A7Fv9wE7i/d0MGl9KrCuT6+3TpkRtXa+EMZ6mbOpPorymTX4qHFwmIK9JlxSJ4L4eP1g036Oin4ssY15A+a9vVeF8MhT43aEfUEZrqfM5kbot2bqfnb738ypdUMbBbkMPTIWJaJC8gselA=
matrix:
  include:
  - osx_image: xcode10
    env: SCHEME="BXUIKit-macOS" DESTINATION="platform=macOS,arch=x86_64"
  - osx_image: xcode10
    env: SCHEME="BXUIKit-iOS" DESTINATION="platform=iOS Simulator,name=iPhone X,OS=latest"
script: set -o pipefail; xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" clean build | xcpretty
notifications:
  slack:
    template:
    - "%{repository_slug}@%{branch} (<%{compare_url}|%{commit}>) by %{author} %{result} in %{duration}"
    secure: PZMdpywwTbvaOh7rfDQPzEqeNj4lWYM9c4jc/J/J+wjmrnGK/Cwqe9ncTcTxhklBDZ9vjhZyjBZf8SvcsoT63XgSaB31foHIev+hIBKyFqm3ChE6L8Y4KwxkQkoArr7M8jdoh5zFJZfv82ECVHkS/d1T3eiyuZOugzOfFlzCFDDY8zha7qwuHJy30bzcEGJfUjmTg6nSiRRIyK00Nu6T2E7WVQS+IKOZlWxLO1KuJtYsmBmMW0Pbml/myufWCxba/g+KuxG340FJ+pTQQdbSWOhKviRr+aKkpx8ZyP6iVcD4cc/5dfaFwKBNKJXHm0Dr48cxlkZwTjcIw6yTxu5GZdfRzPlA4J5hKEH9nPrX5r187LYjt3ThvMp8JFzPLWusw4VWYSNOmtNzYKzgUqzel53V/TFnVv25efuBqgsp9iWICO3sbONhGqPvQf3ZXs7hDqbqklQ79T2BPfA+6tqX296LTjA01JFrh6gmlPQo31c19ix8uzaZCIByPafyU2AijuYl0jdD0JMJOi+WLRfYSwmq0fUOkLDuorgKJGg+Mb2+0se9wSgVhEbB0i4ijOU0pXTYqbSuj9OwHQAZDwNRWG3/ZrD0/9VEsNRYGSvvlrlg8VeLgIcEzIRnYTBe9BnIORP60z8PDbD4uoyhHFJezTymiKcddpX7QhKOPRRoO7w=
